// src/components/footer/footer.tsx
import { HomeUrl } from "../../constants";

const Footer = () => {
  return (
    <footer className="footer row center" id="footer">
      <div className="col-md-4">
        <p className="copyright">
          Copyright &copy; <a href={HomeUrl.url}>{HomeUrl.title}</a>{" "}
          <span>{new Date().getFullYear()}</span>
        </p>
      </div>
    </footer>
  );
};

export default Footer;

// src/lib/footer.svelte
<footer class="footer" id="footer">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-md-4">
				<span class="copyright">
					Copyright &copy; <a href="https://emerson.run">emerson.run</a>
					<span>{new Date().getFullYear()}</span>
				</span>
			</div>

			<div class="col-md-4">
				<ul class="list-inline social-buttons" />
			</div>

			<div class="col-md-4" />
		</div>
	</div>
</footer>
