// src/lib/home.svelte
<script>
	import { Links } from '../constants';
</script>

<section class="page-section" id="services">
	<div class="container">
		<div class="row">
			<div class="col-lg-12 text-center">
				<h3 class="section-heading text-uppercase">Links</h3>
			</div>
		</div>
		{#each Links as link (link.url)}
			<div class="row m-3">
				<div class="col-lg-12 text-center">
					<a class="btn btn-xl btn-secondary text-uppercase" href={link.url} target="_blank">
						{link.title}
					</a>
				</div>
			</div>
		{/each}
		<div class="row text-center" />
	</div>
</section>

// src/pages/home/home.tsx
import 'react';

import { Links } from '../../constants';

export const Home = () => {
    return (
        <>
            <section className="page-section" id="services">
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12 text-center">
                            <h3 className="section-heading text-uppercase">
                                Links
                            </h3>
                        </div>
                    </div>
                    {Links.map((link) => {
                        return (
                            <div className="row" key={link.title} style={{
                                marginBottom: 10,
                            }}>
                                <div className="col-lg-12 text-center" >
                                    <a
                                        style={{
                                            marginBottom: 10,
                                            width: 200
                                        }}
                                        className="btn btn-xl btn-secondary text-uppercase"
                                        href={link.url}
                                        target='_blank'
                                    >
                                        {link.title}
                                    </a>
                                </div>
                            </div>
                        );
                    })}
                    <div className="row text-center"></div>
                </div>
            </section >
        </>
    )
}
